apiVersion: v2
name: silverbullet
description: A Helm chart for SilverBullet - a modern, self-contained note-taking and personal knowledge management system
type: application
version: 0.4.0
appVersion: "2.5.2"
home: https://silverbullet.md
sources:
  - https://github.com/silverbulletmd/silverbullet
keywords:
  - silverbullet
  - notes
  - wiki
  - knowledge-management
  - markdown
icon: https://raw.githubusercontent.com/silverbulletmd/silverbullet/refs/heads/main/client/images/favicon.png
