{{- if and (or .Values.silverbullet.auth.username .Values.silverbullet.auth.password .Values.silverbullet.auth.token) (not .Values.silverbullet.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silverbullet.fullname" . }}-auth
  labels:
    {{- include "silverbullet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.silverbullet.auth.username .Values.silverbullet.auth.password }}
  sb-user: {{ printf "%s:%s" .Values.silverbullet.auth.username .Values.silverbullet.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.silverbullet.auth.token }}
  sb-token: {{ .Values.silverbullet.auth.token | b64enc | quote }}
  {{- end }}
{{- end }}
